### ISSUE TITLE
Update TLS cert

### ISSUE THREAD

**Issue by vanten-s** [CCSleep/ccsleep-web#1]
Hi!

Your TLS certificate is invalid :/

/vanten

**Comment by CCSleep** [comment]
sorry for the late response!

currently this web has gone unmaintained for a while, I have to ask my web admin to update on that since I can't access the server panel for a while. you might need to wait for a few days until i can resolve the problem

anyways, thanks for noticing! :) I really appreciate it.

**Comment by CCSleep** [comment]
Resolved
